# These are supported funding model platforms
funding:
  # If you'd like to support my work, you can do so here:
  # PayPal
  paypal: https://www.paypal.me/hlnaji
  # Patreon
  patreon: http://patreon.com/hlnajz
