# These are supported funding model platforms

<!-- If you'd like to support my work, you can do so here: -->
<!-- PayPal -->
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://www.paypal.me/hlnaji)

<!-- Patreon -->
[![Support me on Patreon](https://img.shields.io/badge/Patreon-Become%20a%20Patron-orange.svg)](http://patreon.com/hlnajz)
